[package]
name = "chip-8"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
log = "0.4.20"
pretty_env_logger = "0.5.0"
dotenv = "0.15.0"
rand = "0.8.5"

[dependencies.clap]
version = "4.4.11"
features = ["derive"]

[dependencies.bevy]
version = "0.12"